In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("train.csv")
df.columns.values

array(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination',
       'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa',
       'VRDeck', 'Name', 'Transported'], dtype=object)

In [3]:
df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0001_01     Europa     False  B/0/P  TRAPPIST-1e  39.0  False   
1     0002_01      Earth     False  F/0/S  TRAPPIST-1e  24.0  False   
2     0003_01     Europa     False  A/0/S  TRAPPIST-1e  58.0   True   
3     0003_02     Europa     False  A/0/S  TRAPPIST-1e  33.0  False   
4     0004_01      Earth     False  F/1/S  TRAPPIST-1e  16.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0        False  
1         True  
2        False  
3        False  
4         True

In [4]:
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [5]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [6]:
test_df=pd.read_csv("test.csv")
test_df.columns.values
test_df.isnull().sum()
test_df.head()

PassengerId HomePlanet CryoSleep  Cabin  Destination   Age    VIP  \
0     0013_01      Earth      True  G/3/S  TRAPPIST-1e  27.0  False   
1     0018_01      Earth     False  F/4/S  TRAPPIST-1e  19.0  False   
2     0019_01     Europa      True  C/0/S  55 Cancri e  31.0  False   
3     0021_01     Europa     False  C/1/S  TRAPPIST-1e  38.0  False   
4     0023_01      Earth     False  F/5/S  TRAPPIST-1e  20.0  False   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0          0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1          0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2          0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3          0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4         10.0        0.0         635.0     0.0     0.0   Brence Harperez

In [18]:
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.impute import SimpleImputer
import pandas as pd
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import StandardScaler
class ExperimentalTransformer(BaseEstimator,TransformerMixin):
    def __init__(self):
        pass
    def fit(self,X,y=None):
        return self
    def transform(self,X,y=None):
        X_= test_df.copy()
        A=X_[['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age','VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']]
        imp_mf = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
        Home_Planet=A['HomePlanet'].array.reshape(-1, 1)
        imp_mf.fit(Home_Planet)
        Home_Planet_transformed=imp_mf.transform(Home_Planet)
        Home_Planet_imputed_final=pd.DataFrame(Home_Planet_transformed,columns=['HomePlanet'])
        dummy1 = pd.get_dummies(Home_Planet_imputed_final, drop_first=True)
        imp_mf1 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
        Cryo_Sleep=A['CryoSleep'].array.reshape(-1, 1)
        imp_mf1.fit(Cryo_Sleep)
        Cryo_Sleep_transformed=imp_mf1.transform(Cryo_Sleep)
        Cryo_Sleep_imputed_final=pd.DataFrame(Cryo_Sleep_transformed,columns=['CryoSleep'])
        Cryo_Sleep_imputed_final = Cryo_Sleep_imputed_final.astype(int)
        imp_mf2 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
        Destination=A['Destination'].array.reshape(-1, 1)
        imp_mf2.fit(Destination)
        Destination_transformed=imp_mf.transform(Destination)
        Destination_transformed=pd.DataFrame(Destination_transformed,columns=['Destination'])
        dummy2 = pd.get_dummies(Destination_transformed, drop_first=True)
        imp_mf3 = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
        VIP=A['VIP'].array.reshape(-1, 1)
        imp_mf1.fit(VIP)
        VIP_transformed=imp_mf1.transform(VIP)
        VIP_imputed_final=pd.DataFrame(VIP_transformed,columns=['VIP'])
        VIP_imputed_final = VIP_imputed_final.astype(int)
        IQR =A['Age'].quantile(0.75)-A['Age'].quantile(0.25)
        value=A['Age'].quantile(0.75)+(1.5*IQR)
        Age_final=A['Age']=A['Age'].fillna(value)
        rest=A[['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']]

        for var in rest:
            IQR =rest[var].quantile(0.75)-rest[var].quantile(0.25)
            value=rest[var].quantile(0.75)+(1.5*IQR)
            rest[var]=rest[var].fillna(value)
        features = pd.concat([dummy1, Cryo_Sleep_imputed_final,dummy2,Age_final,VIP_imputed_final,rest], axis=1)
        transformer = FunctionTransformer(np.sqrt)
        transformer.fit(features)
        X_transformed=transformer.transform(features)
        scaler=StandardScaler()
        X= scaler.fit_transform(X_transformed)
        

    

        

        return X

        
        


In [19]:
obj = ExperimentalTransformer()
obj.transform(test_df)

/tmp/ipykernel_465/531264912.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Age_final=A['Age']=A['Age'].fillna(value)
/tmp/ipykernel_465/531264912.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rest[var]=rest[var].fillna(value)


array([[-0.55313127, -0.52531386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603],
       [-0.55313127, -0.52531386, -0.75162953, ..., -0.51210587,
         2.93401347, -0.45864603],
       [ 1.80788912, -0.52531386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603],
       ...,
       [-0.55313127,  1.90362386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603],
       [ 1.80788912, -0.52531386, -0.75162953, ..., -0.51210587,
        -0.49390451,  0.97827968],
       [-0.55313127, -0.52531386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603]])

In [10]:
y=df['Transported']

y = y.astype(int)


In [9]:
import pickle
pickle.dump(obj,open('preprocessing_for_test.pkl','wb'))

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
model= RandomForestClassifier(n_estimators = 1000)
X=obj.transform(df)
grid2 = {'max_depth':[10,15,300]}
bestmodel = GridSearchCV(model, grid2, cv = 5)
bestmodel.fit(X, y)
print(bestmodel.score(X,y))
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression(penalty = 'l2', max_iter = 100000,random_state=42,C=10)

grid1 = {'solver':['lbfgs', 'newton-cg', 'sag']}

bestLogReg = GridSearchCV(log_model, grid1, cv= 5)
bestLogReg.fit(X, y)
print(bestLogReg.score(X,y))

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

bag_clf=BaggingClassifier(DecisionTreeClassifier(max_depth=20),n_estimators=10,max_samples=800,bootstrap=True)
bag_clf.fit(X,y)
print(bag_clf.score(X,y))


from sklearn import svm
clf = svm.SVC(kernel='linear')

clf.fit(X, y)
print(clf.score(X,y))


from sklearn.ensemble import VotingClassifier
voting_clf=VotingClassifier(estimators=[('rf',bestmodel),('lr',log_model),('svc',clf),('dt',bag_clf)],voting='hard')
voting_clf.fit(X,y)
print(voting_clf.score(X,y))


/tmp/ipykernel_465/1462326054.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Age_final=A['Age']=A['Age'].fillna(value)
/tmp/ipykernel_465/1462326054.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rest[var]=rest[var].fillna(value)


0.8384907396756011
0.7943172667663637
0.8032900034510526
0.7939721615092603
0.8181295295064995


In [16]:
pickle.dump(voting_clf,open('model.pkl','wb'))

In [17]:
pickled_model=pickle.load(open('model.pkl','rb'))

In [11]:
pickled_preprocessing_model=pickle.load(open('preprocessing_for_test.pkl','rb'))

In [20]:
X_test_final_1=pickled_preprocessing_model.transform(test_df)
X_test_final_1

/tmp/ipykernel_465/531264912.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Age_final=A['Age']=A['Age'].fillna(value)
/tmp/ipykernel_465/531264912.py:47: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rest[var]=rest[var].fillna(value)


array([[-0.55313127, -0.52531386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603],
       [-0.55313127, -0.52531386, -0.75162953, ..., -0.51210587,
         2.93401347, -0.45864603],
       [ 1.80788912, -0.52531386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603],
       ...,
       [-0.55313127,  1.90362386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603],
       [ 1.80788912, -0.52531386, -0.75162953, ..., -0.51210587,
        -0.49390451,  0.97827968],
       [-0.55313127, -0.52531386,  1.33044268, ..., -0.51210587,
        -0.49390451, -0.45864603]])

In [21]:
pickled_model.predict(X_test_final_1)

array([1, 0, 1, ..., 1, 1, 1])